### ISSUE TITLE
working examples of responders?

### ISSUE THREAD

**Issue by wdcurry** [cruffenach/CRToast#101]
Are there any examples of setting up the responders? I am not quite seeing it (moderately new to iOS) and trying to best layout things to manage remote pushes into an active app. I poked around other libraries that have local blocks for managing taps etc, and get that, but this setup is not sinking in yet. It is crucial that i track the notification payload that must be acted on if the user taps the toast..

**Comment by r-shayestehpour** [comment]
I have this swift code: 
```

static func showToast(message: String, type: NetworkToastType, isLong: Bool = false , completion: (() -> Void)! = nil) {
                
        let v = CRToastInteractionResponder(interactionType: .All, automaticallyDismiss: true) { type in
            CRToastManager.dismissNotification(true)
            print("HELLO!")
        }

        var options : [NSObject: AnyObject] = [
            kCRToastTextKey: message,
            kCRToastFontKey: UIFont(name: "myFont", size: 15)!,
            kCRToastTextAlignmentKey: NSTextAlignment.Center.rawValue,
            kCRToastAnimationInDirectionKey: CRToastAnimationDirection.Top.rawValue,
            kCRToastAnimationOutDirectionKey: CRToastAnimationDirection.Top.rawValue,
            kCRToastInteractionRespondersKey: v
        ]
        
        options[kCRToastNotificationTypeKey] = isLong ? CRToastType.NavigationBar.rawValue : CRToastType.StatusBar.rawValue
        
        options[kCRToastTimeIntervalKey] = isLong ? 4.0 : 1.5
        
        CRToastManager.showNotificationWithOptions(options, completionBlock: completion)
    }

```

I think the interaction responder should dismiss the notification on any user interaction but not only it does not do that, but also the closure is not called("HELLO is never printed on interactions"). What am I doing wrong?

**Comment by kentoh** [comment]
@r-shayestehpour, the corresponding value for the key  `kCRToastInteractionRespondersKey` is an array of responders, so do the following instead:

`kCRToastInteractionRespondersKey: [v]`

**Comment by r-shayestehpour** [comment]
@kentoh  thanks, I'd missed that!

**Comment by patkozlowski** [comment]
For xamarin.iOS Binding: NSArray.FromObjects(v)
