### ISSUE TITLE
Snapshot view animations have artifacts, look glitchy

### ISSUE THREAD

**Issue by navkast** [cruffenach/CRToast#107]
The view that temporarily shows up during the animate-out is quite glitchy with some artifacts. For example, it often shows the iPhone's main screen's top bar instead of the current app's top bar. And for iPhone 6/6+, it shows a zoomed-in version of the status bar which looks awkwardly oversized.

I was able to hot-fix this by doing the following:

Change:
>return underStatusBar ? [[UIApplication sharedApplication].keyWindow.rootViewController.view snapshotViewAfterScreenUpdates:YES] : [[UIScreen mainScreen] snapshotViewAfterScreenUpdates:YES];

to:
>return [[UIView alloc] initWithFrame:CGRectMake(0, 0, 1000, 500)];

under (in crtoast.m):
>static UIView *CRStatusBarSnapShotView(BOOL underStatusBar)

This fixed the animate-out artifact. The CRToast appears to take a screenshot of the iPhone's main screen OR the current screen, and then replaces that with the animate-out view. But if you just return an empty view as I do above, it appears to work OK.

Thoughts?

**Comment by RTimal** [comment]
Why not just take the snapshot of the top most view controller? Thats the one that the toast will be appearing over.
