### ISSUE TITLE
Code in swift?

### ISSUE THREAD

**Issue by milesper** [cruffenach/CRToast#111]
I'm using it on an ios 8 project, and cannot translate the options initialization code into Swift.  I've translated most of it, but the first option, "kCRToastTextKey :"Hello World!"," is giving an error that "'NSString!' does not conform to protocol 'hashable'".  What am I doing wrong?

**Comment by vyanez** [comment]
I can set background color or image, it show an error saying : dictionary literal contains duplicate keys.

**Comment by Ashton-W** [comment]
can you post the code that builds your options dictionary, @vyanez?
