### ISSUE TITLE
Podspec/tag out of date

### ISSUE THREAD

**Issue by dmiedema** [cruffenach/CRToast#118]
There hasn't been a release in quite some time & it seems that there have been quite a few bug fixes since `0.0.7`. 

Also `Versions` is out of date as it only has information up to `0.0.5`

**Comment by trobrock** [comment]
Any chance we can get a release to CocoaPods soon, we have been running a version from github for awhile now and would like to move back to cocoapods.

**Comment by Ashton-W** [comment]
@dmiedema and others, I've pushed some fixes to the bugs I have noticed on iPhone 6 and iOS 8.
If you have some time I'd appreciate you trying it out. Let's get 0.0.8 out!

**Comment by dmiedema** [comment]
I haven't had a chance to super extensively test it however everything in the demo app seemed to work fine. I'll keep testing it when I have more time, hopefully I'll have some time this week to dedicate to testing it more thoroughly. So far a big :+1: from me.

**Comment by mr-v** [comment]
Would it be possible to bump podspec version now? I'm currently using :head, because it has a fix for iPad issue that is present in 0.0.7. Each time I do `pod update` branch gets downloaded, it adds about 15 seconds on each run.
