### ISSUE TITLE
Status bar animation shifted in iPhone 6

### ISSUE THREAD

**Issue by esusatyo** [cruffenach/CRToast#127]
I am building an app with Xcode 5, which is not yet compatible with iPhone 6. When it's run on iPhone 6, the app is scaled up. 

When the notification is automatically dismissed, the position and size of the clock on the status bar seems to be incorrect.

The video below shows the issue: http://cl.ly/2W473Y1m3J19

**Comment by Ashton-W** [comment]
I'd recommend supporting the iPhone 6 in your app.
CRToast works by being on top of your app, instead of a view inside of it. So we go by the devices reported screen size and resolution.

A pull request is welcome, but scaled apps have lots of problems and it is best to keep up with Apple.

**Comment by esusatyo** [comment]
Ok, thanks Ashton. Cheers.
