### ISSUE TITLE
Unobtrusive Progress Bar

### ISSUE THREAD

**Issue by jadar** [cruffenach/CRToast#129]
It'd be great to have the ability to show a very unobtrusive progress bar toast. It could either be over the status bar, or a few pixels under the navigation bar. It'd be great for when you need to do a sort of lengthy operation and need to show the app is working while still letting the user navigate the app. I'd also like to not have to build a CRToast and progress view hybrid. Also, I think this feature would be much appreciated by others too.

**Comment by Ashton-W** [comment]
I won't say no to a good pull request ;)

But, I do think it is an unusual place for a progress bar. If I was going to put a progress bar up there somewhere it would be inside the navigation bar - where the subtitle text goes.

**Comment by jadar** [comment]
Okay, good. The purpose of this issue was more of a way to check it would be a good idea before doing the work.

Hmm, would the bar look better inside the nav bar, rather than take up a few pixels under it?

Under the navigation bar:
![undernav](https://cloud.githubusercontent.com/assets/3793928/5939994/76215bda-a6cd-11e4-82c5-f6d6f399452c.png)

Inside the navigation bar:
![innav](https://cloud.githubusercontent.com/assets/3793928/5940007/8923e8ba-a6cd-11e4-87b8-e4132e4c216d.png)
