### ISSUE TITLE
Should use UIInterfaceOrientationIsPortrait instead of UIDeviceOrientationIsPortrait

### ISSUE THREAD

**Issue by waterskier2007** [cruffenach/CRToast#133]
I am getting warnings that where UIDeviceOrientation is expected, we are passing a UIInterfaceOrientation.

Should UIInterfaceOrientationIsPortrait be used instead of UIDeviceOrientationIsPortrait (also one occurrence of IsLandscape) or should we just cast the UIInterfaceOrientation as UIDeviceOrientation?

**Comment by dmiedema** [comment]
Where about in the code are you getting these warnings or are there any custom build settings/warning flags you have enabled? I can't seem to get them to show up in the demo project.

It looks like `UIInterfaceOrientation` is defined as the values from `UIDeviceOrientation`. [UIInterfaceOrientation Definition](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIApplication_Class/index.html#//apple_ref/c/tdef/UIInterfaceOrientation)

I don't think we'll want device orientation in case the device is landscape but the interface is in portrait. Looks like we should use `UIInterfaceOrientation` if we want to check the actual layouts orientation [source](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIKitFunctionReference/index.html#//apple_ref/c/macro/UIInterfaceOrientationIsPortrait)

**Comment by waterskier2007** [comment]
There are three references from line 280 to 317 in CRToast.m

I think the issue is that while UIInterfaceOrientation is defined as UIDeviceOrientation, the opposite is not true (at least when it comes to the compiler) so it throws an error. I have just cast the UIInterfaceOrientation values as UIDeviceOrientation and this works and also silences the warning

Here's a screenshot of the error: http://i.imgur.com/YhJMyNJ.png

I don't have any custom build settings that would cause this, and no custom warning flags.

**Comment by dmiedema** [comment]
Odd, I can't seem to get that warnings even with `-Weverything` enabled. The code is unchanged even in the current `master` branch too. Perhaps someone else would like to weigh in? I'm not apposed to the change, especially if it fixes a warning but its not my call. If you want to submit a PR I'm sure it'd be welcomed

**Comment by arnaudmeunier** [comment]
Getting similar errors since I switched to XCode 6.3
Which version of XCode are you using?
