### ISSUE TITLE
Can't build Master in my project

### ISSUE THREAD

**Issue by apanagar** [cruffenach/CRToast#138]
The podspec is out of date (and different from the code in the CRToast Example), so I tried building from master. I pulled CRToast into my project and tried to build, these are the errors I got in CRToastManager.m -

![screen shot 2015-03-02 at 9 56 05 am](https://cloud.githubusercontent.com/assets/180389/6443127/da6f815c-c0c2-11e4-8b90-de0809faafeb.png)

Is there something I need to do? 
The CRToast files are being built with ```-fobjc-arc```, the deployment target is iOS 7.0

Thanks again,
-ajay

**Comment by jadar** [comment]
You need to switch the C Language Dialect in your project Build Settings to "GNU99"
![screen shot 2015-03-02 at 9 11 03 am](https://cloud.githubusercontent.com/assets/3793928/6443397/40ddedae-c0bc-11e4-91b9-2904b8a60ad9.png)

**Comment by apanagar** [comment]
thanks for the quick response and the sharp eye.
