### ISSUE TITLE
APP will be reject because it blocks status bar.

### ISSUE THREAD

**Issue by ch8908** [cruffenach/CRToast#140]
I've been reject twice because of following reason:
```
After further review, we notice that your app does not comply with the Apple iOS Human Interface Guidelines. 

Specifically, we noticed that your app provides an overlay that partially or totally blocks the status bar.
```
So, using it carefully.

**Comment by Ashton-W** [comment]
How often are you obscuring the status bar? Could you show screenshots of your app? We can talk privately if you wish.

Apps have been overlaying the statusbar for some time now, for example Mailbox. Bad :apple:

**Comment by ch8908** [comment]
Only 0.5 sec, this is my UI looks like:

![temp__ryzqglww](https://cloud.githubusercontent.com/assets/2366949/6795141/de23b98e-d216-11e4-8ea1-102e36101c50.jpg)

**Comment by Ashton-W** [comment]
are there any toasts for failure to login? Sadly the app reviews can be a bit random, you can change your alerts or try submission again.

**Comment by Ashton-W** [comment]
Poke @cruffenach

**Comment by summerblue** [comment]
Same problem here, just got rejected by :apple: !
![image](https://cloud.githubusercontent.com/assets/324764/7622671/26158c80-fa04-11e4-8284-3928c87a191d.png)

**Comment by Ashton-W** [comment]
Sorry to hear that @summerblue, all I can suggest is to reduce the the time toasts are on screen, and reduce how often you trigger them - consider other ways to show certain messages.
Sadly reviews are just not consistent.

**Comment by summerblue** [comment]
Yep, My solution is find a way to remove the toasts while App is in review.

Bad :apple: 

@Ashton-W You are awesome! :+1:
