### ISSUE TITLE
Enhancement --- It will be great to have toast at bottom of screen or below the navigation bar

### ISSUE THREAD

**Issue by hardikamal** [cruffenach/CRToast#153]
It will be great to have toast at bottom of screen like android snackbar or below the navigation bar like crouton library in android to avoid app rejection of covering the status bar...Thanks

**Comment by Ashton-W** [comment]
Thanks for the suggestion, but we would like keep CRToast focused on notifications within the navigation bar. There are a few other libraries that provide notifications that might have this feature.

**Comment by hardikamal** [comment]
Ohk... but it will be a good thing if the developer is allowed to change the position based on requirement whether to show on navigation bar or on the view below it.... Anyways thanks for the awesome library

**Comment by yoiang** [comment]
@hardikamal We've added support for bottom of the screen notifications in our fork, check it out here: https://github.com/Adorkable/CRToast

**Comment by jadar** [comment]
You should submit a Pull Request with that. It looks pretty cool.

**Comment by hardikamal** [comment]
@yoiang Thanks mate... Can u create a cocoapod of ur fork...??

**Comment by jadar** [comment]
@hardikamal you can always point your Podfile to his repo.

`pod 'CRToast', :git => 'https://github.com/Adorkable/CRToast'`

**Comment by hardikamal** [comment]
@jadar I m new to iOS..Thanks for the information :+1:
