### ISSUE TITLE
Bug in the enum of gesture type

### ISSUE THREAD

**Issue by wizzardchao** [cruffenach/CRToast#167]
CRToastInteractionTypeAll = (CRToastInteractionTypeSwipe, CRToastInteractionTypeTap)

It seems a "|" rather than "," should be there

**Comment by Ashton-W** [comment]
Good pick up, did you want to try a Pull Request?

**Comment by wizzardchao** [comment]
@Ashton-W I'm new to github, so I'm not familiar to the process. I have submit a Pull Request, you can have a look at it.

**Comment by Ashton-W** [comment]
Fixed in #168
