### ISSUE TITLE
Release a new version for CocoaPods

### ISSUE THREAD

**Issue by josh-fuggle** [cruffenach/CRToast#172]
Hello,

Is there any chance of a new version being released soon?
I need a fix in your latest version, so right now I am pointing to your master branch directly. I'm fine with doing this, but I would prefer not to.

Cheers,
Josh

**Comment by Ashton-W** [comment]
We are trying to have a couple of issues resolved before the next release: https://github.com/cruffenach/CRToast/milestones/0.0.8

However, I understand it has been far too long since the last release. I think we will release 0.0.8 as is, soon.

**Comment by marcoscurvello** [comment]
Please release version 0.0.8 as is, then perform updates as they are implemented, there so many nice feats missing in the cocoapods version :cry:

**Comment by ConfusedVorlon** [comment]
+1 to this request. Also, thanks for a really nice project.

**Comment by Ashton-W** [comment]
`0.0.8` has been released.

**Comment by josh-fuggle** [comment]
Thanks a lot for this Ashton. And good job with the library, will recommend in the future.
