### ISSUE TITLE
Building with Carthage

### ISSUE THREAD

**Issue by kazmasaurus** [cruffenach/CRToast#174]
It would be swank if it was possible to build `CRToast` with [`Carthage`](https://github.com/Carthage/Carthage). The Not Good solution I'm using right now is a [fork](https://github.com/kazmasaurus/CRToast/tree/carthage-build) that has a `CRToast.xcodeproj` in the root with it's own target/scheme.

**Comment by Ashton-W** [comment]
Thanks for the suggestion, wasn't sure if there was demand for it. I'll put it in the milestone.

**Comment by daniel-shin1104** [comment]
+1

**Comment by dmiedema** [comment]
I'm not sure if this would be a passable solution but one way I added support was to just add a new `CRToastCarthage.xcodeproj` that references the `CRToast` files that way the current cocoa pods setup isn't linked to it (and that way I left the example/demo project alone).

**Comment by Ashton-W** [comment]
Yeah that is all that is needed
