### ISSUE TITLE
Conflict with KLCPopup?

### ISSUE THREAD

**Issue by ghysrc** [cruffenach/CRToast#178]
In my project, I have both CRToast and KLCPopup( https://github.com/jmascia/KLCPopup ).
Now the problem is, once I showed a toast, the popup will never show up again.
I tried other similar notification view ,like TSMessages( https://github.com/KrauseFx/TSMessages ). It works all right, and KLCPopup too.
But I prefer CRToast than TSMessages, so I need some help to solve this problem.

**Comment by dmiedema** [comment]
Best i can guess it looks like KLCPopup is adding itself to the top window which CRToast adds its own window on top so that toast messages always appear on top

One of the codebases would need to be modified if that is the case for both to be supported simultaneously

**Comment by jadar** [comment]
You could make it bring the window to front every time it shows a toast.."
