### ISSUE TITLE
CRToast/CRToastConfig.h not found with angled include when installing with CocoaPods

### ISSUE THREAD

**Issue by alatyshev** [cruffenach/CRToast#184]
Getting compile error when angled include in CRToast.h line: 16 #import <CRToast/CRToastConfig.h>

Changing it to quotes fixes the issue.

**Comment by Ashton-W** [comment]
How are you installing CRToast? CocoaPods, Carthage, or other?

**Comment by alatyshev** [comment]
CocoaPods, sorry forgot to mention it in the ticket.

**Comment by Ashton-W** [comment]
Could you share the line your `Podfile` that specifies CRToast, I'm guessing it's something like `pod 'CRToast', :head` ? Are you using frameworks too?

**Comment by alatyshev** [comment]
Yes, it is: pod 'CRToast', :head

It worked this way just last Friday and from yesterday gives compile error.

**Comment by Ashton-W** [comment]
If you pod install again now does it work, I just pushed a new version with a corrected podspec

**Comment by alatyshev** [comment]
It works now, thank you!

**Comment by wanbok** [comment]
This issue is revived from CocoaPod 1.0
![image](https://cloud.githubusercontent.com/assets/68603/13452482/7e0fcdc4-e08b-11e5-9688-a762c06c13b9.png)
