### ISSUE TITLE
Image Size

### ISSUE THREAD

**Issue by rad182** [cruffenach/CRToast#186]
Hi, is it possible to set image size? currently it's using the size of the image itself. problem with this if i have an image from the web i want to show in CRToast and want to use the x2 version of the image for retina. Any possible solution for this?

**Comment by Ashton-W** [comment]
Right now you will need to resize the image in code

**Comment by rad182** [comment]
@Ashton-W that's what i did. I want to show the image as 40x40 but the original image size is 80x80 so it won't be blurry for retina devices. I tried to resize to image to 80x80 it shows the image as 80x80 points still it's blurry. i think the CRToast image is using the image size itself. let me know if i'm doing something wrong.

**Comment by DhiruServer** [comment]
how do i Set image on Toast and its showing very small , i think the Reason is Slide over status bar is not customized , how can i show this toast on overlay of  ViewController ??

**Comment by rad182** [comment]
@Ashton-W is there a fix for workaround for this already?
