### ISSUE TITLE
how to define customer view(can change any position in the main screen )

### ISSUE THREAD

**Issue by lenvonsam** [cruffenach/CRToast#189]
hi cruffenach:
 how can i setting customer view in this plugin

**Comment by kmuddapu** [comment]
Hello Cruffenach,

How can I present Toast  from bottom of the screen.

**Comment by Ashton-W** [comment]
Hi @kmuddapu, toasts from the bottom are not supported in this library, this library mainly deals with animations involving the status and navigation bars at the top of the screen.
