### ISSUE TITLE
CRToast should build without warnings

### ISSUE THREAD

**Issue by iosdev-republicofapps** [cruffenach/CRToast#218]
Hi,

Awesome pod, thanks for releasing this!  :-)

We like to have clean builds without warnings but cannot because CRToast generates build warnings in Xcode Version 8.2.1 (8C1002):

/Users/joel/src/GetLive/Pods/CRToast/CRToast/CRToastManager.h:45:9: Parameter 'options' not found in the function declaration

/Users/joel/src/GetLive/Pods/CRToast/CRToast/CRToastManager.h:68:9: Parameter 'identifier' not found in the function declaration

I think these are just code doc issues.  I could generate a PR to fix if you'd be willing to review and issue a release?  :-)

Thanks!

**Comment by Ashton-W** [comment]
A PR would be welcome

**Comment by iosdev-republicofapps** [comment]
Will do, thanks!
