### ISSUE TITLE
Toast won't disappear on ios 11

### ISSUE THREAD

**Issue by liukaiyi54** [cruffenach/CRToast#221]
I updated my phone to ios 11 beta. And I found that when I display the toast it got stuck on the top and did not go away like it used to. Anyone knows how to solve this?

**Comment by russellquinn** [comment]
Looks like the UICollisionBehaviorDelegate no longer gets called for the CRToastAnimationTypeGravity. Something changed with Apple's implementation of it.

**Comment by russellquinn** [comment]
Or something changed in iOS that means CRToast's calculations in `inCollisionPoint1` and `inCollisionPoint2` are no longer valid.

**Comment by russellquinn** [comment]
Hmm, I started to dig further into this, then I got a notification that iOS 11 beta 3 was out, I updated my device and it looks like it's fixed!! Weird timing. Can anyone else confirm?

**Comment by skuske** [comment]
I observed this issue, too, but on 11.0.1, and not all the time. It only seems to appear sometimes. However: any way to fix that?

**Comment by russellquinn** [comment]
Everything is still working fine for me on 11.0.1. This was only an issue on iOS 11 betas 1 and 2 and happened every time not intermittently. Yours might be a different issue?

**Comment by liukaiyi54** [comment]
Everything's working now. Thanks for the reply, really appreciated it.
