### ISSUE TITLE
Please Disable Code Coverage

### ISSUE THREAD

**Issue by carlosjrtee** [cruffenach/CRToast#225]
Code coverage has to be disabled for Carthage to work with Xcode 9.

Check Carthage/Carthage#2056 and Carthage/Carthage#2057.

**Comment by Ashton-W** [comment]
I'd rather wait for Carthage to fix this, as per their README. Alternatively, use CocoaPods as they recommend

> Ultimately, we created Carthage because we wanted the simplest tool possible—a dependency manager that gets the job done without taking over the responsibility of Xcode, and **without creating extra work for framework authors**. CocoaPods offers many amazing features that Carthage will never have, at the expense of additional complexity.
