### ISSUE TITLE
NSInternalInconsistencyException

### ISSUE THREAD

**Issue by kutluturk** [cruffenach/CRToast#40]
I am calling CRToast from UIViewcontroller with below code;

 (void) userParamsSaved {
    NSDictionary *options = @{
                              kCRToastTextKey : @"Hello World!",
                              kCRToastTextAlignmentKey : @(NSTextAlignmentCenter),
                              kCRToastBackgroundColorKey : [UIColor redColor],
                              kCRToastAnimationInTypeKey : @(CRToastAnimationTypeGravity),
                              kCRToastAnimationOutTypeKey : @(CRToastAnimationTypeGravity),
                              kCRToastAnimationInDirectionKey : @(CRToastAnimationDirectionLeft),
                              kCRToastAnimationOutDirectionKey : @(CRToastAnimationDirectionRight)
                              };
    [CRToastManager showNotificationWithOptions:options
                                completionBlock:^{}];
     
   
}
and get

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid size {320, 0} for item <CRToastView: 0x1093935f0; frame = (-320 0; 320 0); userInteractionEnabled = NO; layer = <CALayer: 0x10932fd70>> in Dynamics'

what i am missing?

**Comment by spencerdcarlson** [comment]
@postmechanical using `kCRToastNotificationTypeKey : CRToastType.NavigationBar.rawValue` also fixed this issue for me. Thanks

**Comment by LegoTechApps** [comment]
**StatusBar must be visible**

`kCRToastNotificationTypeKey: [UIApplication sharedApplication].isStatusBarHidden?@(CRToastTypeNavigationBar):@(CRToastTypeStatusBar)
`
