### ISSUE TITLE
Don't redisplay toast that is already showing

### ISSUE THREAD

**Issue by onato** [cruffenach/CRToast#76]
I needed the following hack in order to prevent the same toast message from being displayed over and over.

```objective-c
id manager = [CRToastManager valueForKeyPath:@"manager"];
id notification = [manager valueForKeyPath:@"notification"];
NSString *existingTitle = [notification valueForKeyPath:@"text"];
NSString *existingSubtitle = [notification valueForKeyPath:@"subtitleText"];
if ([existingTitle isEqualToString:title] && [existingSubtitle isEqualToString:message]) {
    return;
}
```

The problem is that if the same message is displayed often, it keeps animating away and back again. I would prefer that it is ignored or that the old toast is replaced without animation.

Is there a better way of achieving my goal?

**Comment by raulriera** [comment]
It's been a year, but I really like @onato approach of letting the Pod itself handle this situation. Instead of relaying on boolean states in the view controllers.

**Comment by onato** [comment]
The code I supplied above works fine, it just seems clunky that for a legitimate use case, I have to access private fields. 

Could we make them public and readonly?

**Comment by dmiedema** [comment]
I don't think I understand the current issue. 

The code above was just show that the feature was available. I wouldn't want to use `valueForKeyPath:` like that in production just to show or not show a toast notification.

You shouldn't have to access private fields -- the `notificationIdentifiersInQueue` is a public method on `CRToastManager` ([header](https://github.com/cruffenach/CRToast/blob/master/CRToast/CRToastManager.h#L73-L77)).

In my use case I usually use set the text of the toast to the identifier. I built the feature based on the previous discussion on the issue, specifically [cruffenach comment](https://github.com/cruffenach/CRToast/issues/76#issuecomment-47718512).

**Comment by raulriera** [comment]
Your repo doesn't appear to still be alive @dmiedema

**Comment by dmiedema** [comment]
@raulriera its currently in `master` of this repo - the change was merged in so i deleted my forks branch

**Comment by raulriera** [comment]
Thanks, I was using an old version of the pod. Now I have the version from master.. too bad this was never released

**Comment by onato** [comment]
OK, I get it now. Can be closed as far as I'm concerned. Nice work.
