### ISSUE TITLE
The toast is dismissible with a swipe even if the responder is not set

### ISSUE THREAD

**Issue by jschmid** [cruffenach/CRToast#91]
I have this error with the demo app. 
If you check "Dismissible with Tap" then show a toast, you are able to dismiss it with a tap. The console then shows:

    Dismissed with Tap Once interaction

However, you can also dismiss it with a swipe:

    Dismissed with Swipe Left interaction

Which you should not be able to do.

**Comment by AdamCampbell** [comment]
Confirming that this seems to be fixed by #115

**Comment by Ashton-W** [comment]
Thanks @AdamCampbell!
